{% set name = "backpack-for-pytorch" %}
{% set version = "1.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/backpack-for-pytorch-{{ version }}.tar.gz
  sha256: e58a6a498ad47071d3f27f7adc2ef0b9c814199b24f368e86ed58bfa35a6429b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - sysroot_linux-64 ==2.17                # [linux64]
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - einops >=0.3.0
    - python >=3.7
    - pytorch >=1.9.0
    - torchvision >=0.7.0

test:
  imports:
    - backpack
    - backpack.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/f-dangel/backpack
  summary: 'BackPACK: Packing more into backprop'
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Tobias-Fischer
